import http from 'node:http';
import path from 'node:path';
import {readFileSync,mkdirSync,writeFileSync,existsSync,unlinkSync} from 'node:fs';
import {readFile,stat} from 'node:fs/promises';
import {randomUUID,randomBytes,createHash,createHmac,scrypt,timingSafeEqual} from 'node:crypto';
import {promisify} from 'node:util';
import {openStore,stateRow,saveState,validateState,transaction,fail,collections} from './store.mjs';
import {vault,configFor,connectionStatus,providerNames,cosReply,remote,safeEndpoint} from './providers.mjs';
const derive=promisify(scrypt),hash=x=>createHash('sha256').update(x).digest('hex'),id=()=>randomUUID(),now=()=>Date.now();
const equal=(a,b)=>{const x=Buffer.from(a||''),y=Buffer.from(b||'');return x.length===y.length&&timingSafeEqual(x,y);};
const cleanText=(v,max=500)=>typeof v==='string'?v.trim().slice(0,max):'';
const passwordOK=p=>typeof p==='string'&&p.length>=10&&p.length<=256;
async function passwordHash(p){const salt=randomBytes(16).toString('hex'),key=await derive(p,salt,64);return salt+':'+key.toString('hex');}
async function passwordCheck(p,stored){const [salt,key]=stored.split(':');return equal((await derive(p,salt,64)).toString('hex'),key);}
const mimetypes={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.svg':'image/svg+xml','.woff2':'font/woff2','.mp4':'video/mp4'};
const allowedUploads={'.pdf':'application/pdf','.docx':'application/vnd.openxmlformats-officedocument.wordprocessingml.document','.txt':'text/plain','.md':'text/plain','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg'};
export function createApp({directory,dist,env={},origin}={}){
 const db=openStore(directory),v=vault(directory,env),files=path.join(directory,'uploads');mkdirSync(files,{recursive:true});
 const seed=JSON.parse(readFileSync(new URL('./initial-state.json',import.meta.url),'utf8'));
 const limits=new Map();let address=origin;
 function rate(key,max=50){const ts=now();let r=limits.get(key);if(!r||r.end<ts){r={n:0,end:ts+60000};limits.set(key,r);}if(++r.n>max)fail(429,'Muitas tentativas. Aguarde um minuto.');if(limits.size>5000)for(const[k,x]of limits)if(x.end<ts)limits.delete(k);}
 function initial(agency){const s=structuredClone(seed);s.agency=agency;s.billing.name=agency;const date=new Date();s.month=date.getMonth();s.year=date.getFullYear();s.day=date.toISOString().slice(0,10);return s;}
 function audit(agency,user,action){db.prepare('INSERT INTO audit(agency_id,user_id,action,created_at) VALUES(?,?,?,?)').run(agency,user,action,now());}
 function publicUser(u){return {id:u.id,name:u.name,email:u.email,agencyId:u.agency_id};}
 function session(req){const token=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('travelpro_session='))?.slice(18);if(!token)return null;const s=db.prepare('SELECT s.*,u.agency_id,u.email,u.name FROM sessions s JOIN users u ON u.id=s.user_id WHERE token_hash=?').get(hash(token));if(!s)return null;const pref=stateRow(db,s.agency_id).state.security;const idle=Math.min(60,Math.max(15,Number(pref?.timeout)||30))*60000;if(s.expires_at<now()||s.last_seen<now()-idle){db.prepare('DELETE FROM sessions WHERE id=?').run(s.id);return null;}db.prepare('UPDATE sessions SET last_seen=? WHERE id=?').run(now(),s.id);return s;}
 function cookie(res,token,age=604800){res.setHeader('Set-Cookie',`travelpro_session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=${age}${address?.startsWith('https:')?'; Secure':''}`);}
 function makeSession(req,res,u){const token=randomBytes(32).toString('hex'),sid=id(),csrf=randomBytes(24).toString('hex');db.prepare('INSERT INTO sessions VALUES(?,?,?,?,?,?,?,?)').run(sid,u.id,hash(token),csrf,now(),now(),now()+604800000,cleanText(req.headers['user-agent']||'Cliente HTTP',200));cookie(res,token);return {user:publicUser(u),csrf};}
 function output(res,status,data){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data));}
 async function body(req){let size=0,chunks=[];for await(const part of req){size+=part.length;if(size>8*1024*1024)fail(413,'Solicitação muito grande.');chunks.push(part);}return Buffer.concat(chunks);}
 function parse(buf){try{return buf.length?JSON.parse(buf.toString()):{};}catch{fail(400,'JSON inválido.');}}
 function allowedHost(host){
  const configured=new URL(address);
  if(host===configured.host)return true;
  if(env.NODE_ENV==='production'||configured.protocol!=='http:')return false;
  const local=new Set(['localhost','127.0.0.1','[::1]']);
  try{const candidate=new URL('http://'+host);return candidate.host===host&&local.has(configured.hostname)&&local.has(candidate.hostname)&&candidate.port===configured.port;}catch{return false;}
 }
 function trustedOrigin(req){
  const expected=new URL(address).protocol+'//'+req.headers.host;
  if(req.headers.origin!==expected||!allowedHost(req.headers.host))fail(403,'Origem da solicitação não autorizada.');
 }
 function cfg(agency,service){return configFor(db,v,agency,service,env);}
 function services(agency){return providerNames.map(service=>connectionStatus(service,cfg(agency,service)));}
 async function webhook(req,res,url){
   if(req.method==='GET'){const token=url.searchParams.get('hub.verify_token');if(url.searchParams.get('hub.mode')!=='subscribe'||!token)fail(403,'Verificação inválida.');const rows=db.prepare("SELECT agency_id FROM integration_config WHERE service='whatsapp'").all();if(!rows.some(r=>equal(cfg(r.agency_id,'whatsapp').verifyToken,token)))fail(403,'Verificação inválida.');res.writeHead(200,{'Content-Type':'text/plain'});res.end(url.searchParams.get('hub.challenge')||'');return;}
   if(req.method!=='POST')fail(405,'Método não permitido.');const raw=await body(req),data=parse(raw);let accepted=0;
   for(const entry of data.entry||[])for(const change of entry.changes||[]){const value=change.value||{},phoneId=value.metadata?.phone_number_id;if(!phoneId)continue;let agency,c;for(const row of db.prepare("SELECT agency_id FROM integration_config WHERE service='whatsapp'").all()){const candidate=cfg(row.agency_id,'whatsapp');if(candidate.phoneId===phoneId){agency=row.agency_id;c=candidate;break;}}if(!agency)continue;if(!c.appSecret||!equal(req.headers['x-hub-signature-256'],'sha256='+createHmac('sha256',c.appSecret).update(raw).digest('hex')))fail(403,'Assinatura do webhook inválida.');
    for(const m of value.messages||[]){if(m.type!=='text'||!m.id||!m.from||!m.text?.body)continue;transaction(db,()=>{if(db.prepare('SELECT id FROM webhook_events WHERE id=?').get(m.id))return;const row=stateRow(db,agency),s=row.state;let t=s.whatsapp.threads.find(t=>t.phone.replace(/\D/g,'')===m.from);if(!t){t={id:id(),name:cleanText(value.contacts?.find(x=>x.wa_id===m.from)?.profile?.name||m.from,150),phone:m.from,mode:'cos',lead:s.whatsapp.config.autoLead,clientId:'',draft:'',profile:{destination:'',origin:'',start:'',end:'',travelers:0,budget:0,email:'',notes:''},messages:[],events:['Contato recebido pelo WhatsApp.'],channel:'live'};s.whatsapp.threads.unshift(t);}t.channel='live';t.lastInbound=Number(m.timestamp)*1000||now();t.messages.push({id:m.id,role:'customer',text:cleanText(m.text.body,10000),time:new Date(t.lastInbound).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})});if(/atendente|falar com (uma )?pessoa|humano/i.test(m.text.body)){t.mode='human';t.draft='';t.events.push('Solicitação de atendimento humano.');}else if(t.mode==='closed')t.mode='cos';validateState(s);db.prepare('UPDATE agency_state SET data=?,version=version+1,updated_at=? WHERE agency_id=?').run(JSON.stringify(s),now(),agency);db.prepare('INSERT INTO webhook_events VALUES(?,?,?)').run(m.id,agency,now());if(t.mode==='cos'&&s.whatsapp.config.autoDraft)db.prepare('INSERT INTO jobs(id,agency_id,thread_id,message_id,status,available_at,created_at) VALUES(?,?,?,?,?,?,?)').run(id(),agency,t.id,m.id,'queued',now(),now());accepted++;});}
   }output(res,200,{accepted});
 }
 let runningJob=false;
 async function processJobs(){if(runningJob)return;const job=db.prepare("SELECT * FROM jobs WHERE status IN ('queued','retry') AND available_at<=? ORDER BY created_at LIMIT 1").get(now());if(!job)return;runningJob=true;try{const row=stateRow(db,job.agency_id),thread=row.state.whatsapp.threads.find(t=>t.id===job.thread_id);if(!thread||thread.mode!=='cos'||thread.messages.filter(m=>m.role==='customer').at(-1)?.id!==job.message_id){db.prepare("UPDATE jobs SET status='superseded' WHERE id=?").run(job.id);return;}const c=cfg(job.agency_id,'openai');if(!c.key||!c.model){db.prepare("UPDATE jobs SET status='pending_connection' WHERE id=?").run(job.id);return;}const answer=await cosReply(c,thread.messages.map(m=>({role:m.role==='customer'?'user':'cos',text:m.text})),{agency:row.state.agency,traveler:thread.profile,instructions:row.state.whatsapp.config.instructions});const latest=stateRow(db,job.agency_id),t=latest.state.whatsapp.threads.find(t=>t.id===job.thread_id);if(t?.mode==='cos'&&t.messages.filter(m=>m.role==='customer').at(-1)?.id===job.message_id){t.draft=answer;saveState(db,job.agency_id,latest.state,latest.version);db.prepare("UPDATE jobs SET status='done' WHERE id=?").run(job.id);}else db.prepare("UPDATE jobs SET status='superseded' WHERE id=?").run(job.id);}catch{db.prepare('UPDATE jobs SET status=?,attempts=attempts+1,available_at=? WHERE id=?').run(job.attempts>=2?'failed':'retry',now()+30000*(job.attempts+1),job.id);}finally{runningJob=false;}}
 const jobTimer=setInterval(()=>processJobs().catch(()=>{}),3000);jobTimer.unref();
 const server=http.createServer(async(req,res)=>{
  res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','same-origin');res.setHeader('X-Frame-Options','SAMEORIGIN');
  try{
   const url=new URL(req.url,address||'http://127.0.0.1'),p=url.pathname,method=req.method;
   if(address&&!allowedHost(req.headers.host))fail(403,'Host não autorizado.');
   if(p==='/api/health'){output(res,200,{ok:true,storage:'sqlite',version:2});return;}
   if(p==='/api/webhooks/whatsapp'){await webhook(req,res,url);return;}
   if(!p.startsWith('/api/')){const pathname=decodeURIComponent(p),file=path.resolve(dist,'.'+(pathname==='/'?'/index.html':pathname));if(!file.startsWith(path.resolve(dist)+path.sep)||!mimetypes[path.extname(file)])fail(404,'Não encontrado.');if(!(await stat(file)).isFile())fail(404,'Não encontrado.');res.writeHead(200,{'Content-Type':mimetypes[path.extname(file)],'Cache-Control':'no-cache'});res.end(await readFile(file));return;}
   rate(req.socket.remoteAddress+':api',300);
   if(!['GET','HEAD'].includes(method)){trustedOrigin(req);if(!req.headers['content-type']?.startsWith('application/json'))fail(415,'Use application/json.');}
   const data=['POST','PUT','PATCH','DELETE'].includes(method)?parse(await body(req)):{};
   if(p==='/api/auth/register'&&method==='POST'){
    rate(req.socket.remoteAddress+':register',5);const email=cleanText(data.email,254).toLowerCase(),name=cleanText(data.name,100),agency=cleanText(data.agency,150);if(!name||!agency||!/^\S+@\S+\.\S+$/.test(email)||!passwordOK(data.password))fail(422,'Informe nome, agência, e-mail e senha de 10 a 256 caracteres.');if(db.prepare('SELECT id FROM users WHERE email=?').get(email))fail(409,'Já existe uma conta com esse e-mail.');const password=await passwordHash(data.password),u={id:id(),agency_id:id(),name,email};transaction(db,()=>{db.prepare('INSERT INTO agencies VALUES(?,?,?)').run(u.agency_id,agency,now());db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?)').run(u.id,u.agency_id,name,email,password,now());db.prepare('INSERT INTO agency_state VALUES(?,?,1,?)').run(u.agency_id,JSON.stringify(initial(agency)),now());});output(res,201,makeSession(req,res,u));return;
   }
   if(p==='/api/auth/login'&&method==='POST'){
    rate(req.socket.remoteAddress+':login',10);const email=cleanText(data.email,254).toLowerCase();if(typeof data.password!=='string'||data.password.length>256)fail(401,'E-mail ou senha inválidos.');const u=db.prepare('SELECT * FROM users WHERE email=?').get(email);const valid=await passwordCheck(data.password,u?.password_hash||'00000000000000000000000000000000:'+ '0'.repeat(128));if(!u||!valid)fail(401,'E-mail ou senha inválidos.');audit(u.agency_id,u.id,'auth.login');output(res,200,makeSession(req,res,u));return;
   }
   if(p==='/api/auth/reset-request'&&method==='POST'){
    rate(req.socket.remoteAddress+':reset',5);if(!env.RESET_EMAIL_URL||!env.RESET_EMAIL_KEY)fail(503,'O envio de recuperação ainda não foi configurado. Você pode alterar a senha em Segurança se já estiver conectado.');const u=db.prepare('SELECT * FROM users WHERE email=?').get(cleanText(data.email,254).toLowerCase());if(u){const token=randomBytes(32).toString('hex');db.prepare('INSERT INTO password_resets VALUES(?,?,?)').run(hash(token),u.id,now()+1800000);await remote(safeEndpoint(env.RESET_EMAIL_URL),{method:'POST',headers:{Authorization:'Bearer '+env.RESET_EMAIL_KEY,'Content-Type':'application/json'},body:JSON.stringify({to:u.email,subject:'Recuperar acesso ao TravelPro',text:`Use este link em até 30 minutos: ${address}/login.html?reset=${token}`})});}output(res,200,{message:'Se o endereço estiver cadastrado, você receberá as instruções.'});return;
   }
   if(p==='/api/auth/reset-confirm'&&method==='POST'){rate(req.socket.remoteAddress+':reset-confirm',10);if(!passwordOK(data.password)||typeof data.token!=='string')fail(422,'Informe uma senha válida.');const r=db.prepare('SELECT * FROM password_resets WHERE token_hash=? AND expires_at>?').get(hash(data.token),now());if(!r)fail(400,'Link inválido ou expirado.');const pw=await passwordHash(data.password);transaction(db,()=>{db.prepare('UPDATE users SET password_hash=? WHERE id=?').run(pw,r.user_id);db.prepare('DELETE FROM password_resets WHERE user_id=?').run(r.user_id);db.prepare('DELETE FROM sessions WHERE user_id=?').run(r.user_id);});output(res,200,{ok:true});return;}
   const s=session(req);if(!s)fail(401,'Entre na sua conta para continuar.');const user={id:s.user_id,agency_id:s.agency_id,name:s.name,email:s.email};
   if(!['GET','HEAD'].includes(method)&&!equal(req.headers['x-csrf-token'],s.csrf))fail(403,'Sua sessão precisa ser atualizada. Recarregue a página.');
   if(p==='/api/auth/session'&&method==='GET'){output(res,200,{user:publicUser(user),csrf:s.csrf});return;}
   if(p==='/api/auth/logout'&&method==='POST'){db.prepare('DELETE FROM sessions WHERE id=?').run(s.id);cookie(res,'',0);output(res,200,{ok:true});return;}
   if(p==='/api/auth/password'&&method==='POST'){rate(s.user_id+':password',5);if(!passwordOK(data.password)||typeof data.current!=='string'||data.current.length>256)fail(422,'A nova senha deve ter pelo menos 10 caracteres.');const u=db.prepare('SELECT * FROM users WHERE id=?').get(s.user_id);if(!await passwordCheck(data.current,u.password_hash))fail(403,'Senha atual incorreta.');const pw=await passwordHash(data.password);transaction(db,()=>{db.prepare('UPDATE users SET password_hash=? WHERE id=?').run(pw,s.user_id);db.prepare('DELETE FROM sessions WHERE user_id=?').run(s.user_id);});output(res,200,makeSession(req,res,u));return;}
   if(p==='/api/auth/sessions'&&method==='GET'){const items=db.prepare('SELECT id,created_at,last_seen,user_agent FROM sessions WHERE user_id=? AND expires_at>?').all(s.user_id,now());output(res,200,{sessions:items.map(x=>({...x,current:x.id===s.id}))});return;}
   if(p.startsWith('/api/auth/sessions/')&&method==='DELETE'){const target=p.split('/').at(-1);if(target===s.id)fail(400,'Use Sair para encerrar a sessão atual.');db.prepare('DELETE FROM sessions WHERE id=? AND user_id=?').run(target,s.user_id);output(res,200,{ok:true});return;}
   if(p==='/api/workspace'&&method==='GET'){output(res,200,{...stateRow(db,s.agency_id),services:services(s.agency_id)});return;}
   if(p==='/api/workspace'&&method==='PUT'){if(!Number.isInteger(data.version))fail(422,'Versão ausente.');const version=saveState(db,s.agency_id,data.state,data.version,s.user_id);output(res,200,{version});return;}
   if(p.startsWith('/api/records/')){const [, , ,collection,recordId]=p.split('/');if(!collections.includes(collection))fail(404,'Coleção não encontrada.');const row=stateRow(db,s.agency_id),items=row.state[collection];if(method==='GET'){const result=recordId?items.find(x=>x.id===recordId):items;if(!result)fail(404,'Registro não encontrado.');output(res,200,{data:result,version:row.version});return;}if(data.version!==row.version)fail(409,'Atualize os dados antes de continuar.');if(method==='POST'&&!recordId)items.push({...data.record,id:id()});else if(method==='PATCH'&&recordId){const item=items.find(x=>x.id===recordId);if(!item)fail(404,'Registro não encontrado.');Object.assign(item,data.record,{id:recordId});}else if(method==='DELETE'&&recordId)row.state[collection]=items.filter(x=>x.id!==recordId);else fail(405,'Método não permitido.');const version=saveState(db,s.agency_id,row.state,row.version,s.user_id);output(res,200,{version,data:row.state[collection]});return;}
   if(p==='/api/files'&&method==='POST'){const name=cleanText(data.name,200),ext=path.extname(name).toLowerCase();if(!allowedUploads[ext]||typeof data.base64!=='string')fail(422,'Tipo de arquivo não permitido.');const bytes=Buffer.from(data.base64,'base64');if(!bytes.length||bytes.length>5*1024*1024)fail(413,'Use um arquivo de até 5 MB.');const fid=id();writeFileSync(path.join(files,fid),bytes,{flag:'wx',mode:0o600});try{db.prepare('INSERT INTO uploads VALUES(?,?,?,?,?,?)').run(fid,s.agency_id,name,allowedUploads[ext],bytes.length,now());}catch(e){unlinkSync(path.join(files,fid));throw e;}audit(s.agency_id,s.user_id,'file.uploaded');output(res,201,{id:fid,name,size:bytes.length,type:allowedUploads[ext],url:'/api/files/'+fid});return;}
   if(p.startsWith('/api/files/')&&method==='GET'){const f=db.prepare('SELECT * FROM uploads WHERE id=? AND agency_id=?').get(p.split('/').at(-1),s.agency_id);if(!f)fail(404,'Arquivo não encontrado.');res.writeHead(200,{'Content-Type':'application/octet-stream','Content-Disposition':`attachment; filename*=UTF-8''${encodeURIComponent(f.name)}`,'Cache-Control':'private, no-store'});res.end(await readFile(path.join(files,f.id)));return;}
   if(p==='/api/integrations'&&method==='GET'){output(res,200,{agencyId:s.agency_id,services:providerNames.map(service=>{const c=cfg(s.agency_id,service);return {...connectionStatus(service,c),config:Object.fromEntries(['model','endpoint','phoneId','version'].filter(k=>c[k]).map(k=>[k,c[k]]))};})});return;}
   if(p.startsWith('/api/integrations/')&&method==='PUT'){const service=p.split('/').at(-1);if(!providerNames.includes(service))fail(404,'Integração não encontrada.');const old=cfg(s.agency_id,service),config=data.config||{},secret={};for(const k of ['key','token','appSecret','verifyToken'])if(typeof config[k]==='string'&&config[k])secret[k]=config[k];else if(old[k])secret[k]=old[k];const pub={};for(const k of ['model','endpoint','phoneId','version'])if(typeof config[k]==='string')pub[k]=cleanText(config[k],500);else if(old[k])pub[k]=old[k];if(pub.endpoint)pub.endpoint=safeEndpoint(pub.endpoint);if(pub.phoneId&&!/^\d+$/.test(pub.phoneId))fail(422,'Identificador de telefone inválido.');if(pub.version&&!/^v\d+\.\d+$/.test(pub.version))fail(422,'Use a versão Graph no formato vNN.N.');if(service==='whatsapp'&&pub.phoneId){for(const other of db.prepare("SELECT agency_id FROM integration_config WHERE service='whatsapp' AND agency_id<>?").all(s.agency_id))if(cfg(other.agency_id,service).phoneId===pub.phoneId)fail(409,'Telefone já vinculado a outra agência.');}db.prepare('INSERT INTO integration_config VALUES(?,?,?,?) ON CONFLICT(agency_id,service) DO UPDATE SET public_config=excluded.public_config,secret=excluded.secret').run(s.agency_id,service,JSON.stringify(pub),v.encrypt(secret));if(service==='openai')db.prepare("UPDATE jobs SET status='queued',available_at=? WHERE agency_id=? AND status='pending_connection'").run(now(),s.agency_id);audit(s.agency_id,s.user_id,'integration.configured.'+service);output(res,200,{service,...connectionStatus(service,{...pub,...secret})});return;}
   if(p==='/api/cos/chat'&&method==='POST'){rate(s.user_id+':cos',20);const text=cleanText(data.text,10000);if(!text)fail(422,'Escreva seu pedido.');const row=stateRow(db,s.agency_id);if(data.version!==row.version)fail(409,'O contexto mudou. Atualize antes de conversar.');const history=[...row.state.messages,{role:'user',text}];const context={agency:row.state.agency,clients:row.state.clients.map(c=>({id:c.id,name:c.name})),trips:row.state.trips.map(t=>({title:t.title,destination:t.destination,status:t.status})),events:row.state.events};const answer=await cosReply(cfg(s.agency_id,'openai'),history,context);const q=text.toLowerCase();let action,label,fallback;if(/cliente|lead/.test(q)){action='new-client';label='Cadastrar cliente';fallback=`Você tem ${row.state.clients.length} clientes cadastrados. Posso abrir o cadastro para registrar um novo relacionamento.`;}else if(/roteiro/.test(q)){action='new-itinerary';label='Preparar roteiro';fallback='Vamos preparar um roteiro com um modelo da agência. Escolha o destino e a viagem no formulário.';}else if(/cota|orçamento/.test(q)){action='open-quote';label='Abrir cotação';fallback='Vamos organizar destino, datas e viajantes. As tarifas reais dependem da operadora; você já pode montar orçamentos manuais.';}else if(/campanha|post|instagram/.test(q)){action='new-campaign';label='Abrir Studio';fallback='O Studio permite montar uma campanha com seus modelos. A geração de imagens e vídeo depende do provedor.';}else{action='new-trip';label='Preparar viagem';fallback=`Olá! Sou o COS da ${row.state.agency}. Posso ajudar a organizar clientes, viagens, roteiros e cotações. Estou no modo guiado enquanto a IA não está conectada.`;}const response={role:'cos',text:answer||fallback,action,label,mode:answer?'ai':'guided'};row.state.messages=[...history,response];const version=saveState(db,s.agency_id,row.state,row.version,s.user_id);output(res,200,{response,messages:row.state.messages,version,mode:response.mode});return;}
   if(p==='/api/ai/itinerary'&&method==='POST'){
    rate(s.user_id+':ai-content',10);const row=stateRow(db,s.agency_id),name=cleanText(data.name,150),destination=cleanText(data.destination,200),template=row.state.templates.find(t=>t.id===data.template),linked=row.state.trips.find(t=>t.id===data.trip);if(!name||!destination||!template||(data.trip&&!linked))fail(422,'Revise o roteiro, o modelo e a viagem.');if(data.version!==row.version)fail(409,'Os dados mudaram. Atualize o roteiro.');
    const answer=await cosReply(cfg(s.agency_id,'openai'),[{role:'user',text:'Crie uma proposta de roteiro textual para '+destination+'. Responda apenas JSON no formato {"days":[{"period":"Dia 1","title":"...","text":"..."}]}. Entre 1 e 30 etapas. Sem tarifas, horários de voo ou reservas inventadas. Atividades devem ser sugestões a verificar. '+(linked?'Período: '+linked.start+' a '+linked.end+'. Viajantes: '+linked.travelers:'')}],{agency:row.state.agency,template:{name:template.name},instructions:'Roteiro de inspiração para revisão da agência. Não afirmar que serviços estão reservados.'});if(!answer)fail(503,'Configure a IA em Integrações para gerar roteiros. Você pode usar a estrutura editável sem conexão.');let parsed;try{parsed=JSON.parse(answer.replace(/^```(?:json)?\s*/,'').replace(/\s*```$/,''));}catch{fail(502,'A IA não retornou um roteiro estruturado. Nenhum roteiro foi criado.');}if(!Array.isArray(parsed.days)||!parsed.days.length||parsed.days.length>30||parsed.days.some(d=>!d.period||!d.title||typeof d.text!=='string'))fail(502,'O roteiro retornado está incompleto. Nenhum roteiro foi criado.');const r={id:id(),name,destination,template:template.id,trip:linked?.id||'',days:parsed.days.map(d=>({period:cleanText(d.period,100),title:cleanText(d.title,200),text:cleanText(d.text,10000)})),generated:true};row.state.itineraries.push(r);const version=saveState(db,s.agency_id,row.state,row.version,s.user_id);output(res,201,{id:r.id,version});return;
   }
   if(p==='/api/ai/campaign'&&method==='POST'){
    rate(s.user_id+':ai-content',10);const row=stateRow(db,s.agency_id);if(data.version!==row.version)fail(409,'A campanha mudou. Atualize antes de gerar.');const studio=row.state.studio;const answer=await cosReply(cfg(s.agency_id,'openai'),[{role:'user',text:'Escreva somente uma legenda de até 1000 caracteres para a campanha: '+studio.title+'. Chamada: '+studio.subtitle+'. Sem inventar preços, datas promocionais, serviços inclusos ou disponibilidade.'}],{agency:row.state.agency});if(!answer)fail(503,'Configure a IA em Integrações para gerar legendas.');row.state.studio.caption=answer.slice(0,3000);const version=saveState(db,s.agency_id,row.state,row.version,s.user_id);output(res,200,{caption:row.state.studio.caption,version});return;
   }

   if(p==='/api/operator/quote'&&method==='POST'){const c=cfg(s.agency_id,'operator');if(!c.endpoint||!c.key)fail(503,'Operadora não conectada. Use a cotação ilustrativa ou monte um orçamento manual.');const result=await remote(safeEndpoint(c.endpoint),{method:'POST',headers:{Authorization:'Bearer '+c.key,'Content-Type':'application/json'},body:JSON.stringify({type:'quote',request:data.request})});if(result.currency!=='BRL'||!Array.isArray(result.offers)||result.offers.some(o=>typeof o.name!=='string'||typeof o.total!=='number'||!Number.isFinite(o.total)||o.total<0||!Array.isArray(o.inclusions)||o.inclusions.some(i=>typeof i!=='string')))fail(502,'O adaptador da operadora não retornou o formato esperado.');output(res,200,{offers:result.offers.map(o=>({...o,description:typeof o.description==='string'?o.description:'Consulte as condições da operadora.'})),validUntil:result.validUntil||null,source:'operator'});return;}
   if(p==='/api/whatsapp/draft'&&method==='POST'){const row=stateRow(db,s.agency_id),t=row.state.whatsapp.threads.find(t=>t.id===data.threadId);if(!t)fail(404,'Conversa não encontrada.');if(t.mode!=='cos')fail(409,'A equipe está no atendimento. O agente está pausado.');const c=cfg(s.agency_id,'openai'),messages=t.messages.map(m=>({role:m.role==='customer'?'user':'cos',text:m.text}));const answer=await cosReply(c,messages,{agency:row.state.agency,traveler:t.profile,instructions:row.state.whatsapp.config.instructions});if(!answer)fail(503,'Conecte a IA para preparar respostas livres a contatos reais.');t.draft=answer;const version=saveState(db,s.agency_id,row.state,row.version,s.user_id);output(res,200,{draft:answer,version});return;}
   if(p==='/api/whatsapp/send'&&method==='POST'){const row=stateRow(db,s.agency_id),t=row.state.whatsapp.threads.find(t=>t.id===data.threadId),text=cleanText(data.text,4000);if(!t||t.channel!=='live'||t.mode==='closed'||!text)fail(422,'Selecione um atendimento real aberto e uma resposta.');if(!t.lastInbound||now()-t.lastInbound>86400000)fail(422,'A janela de resposta terminou. O envio por template ainda precisa ser configurado.');const c=cfg(s.agency_id,'whatsapp');if(!connectionStatus('whatsapp',c).configured)fail(503,'WhatsApp não configurado.');const requestId=cleanText(data.requestId,100);if(!requestId)fail(422,'Identificador de envio obrigatório.');const old=db.prepare('SELECT * FROM outbox WHERE id=? AND agency_id=?').get(requestId,s.agency_id);if(old){output(res,200,{status:old.status,remoteId:old.remote_id});return;}db.prepare('INSERT INTO outbox VALUES(?,?,?,?,?,?,?,?)').run(requestId,s.agency_id,t.id,text,'sending',null,now());let result;try{result=await remote(`https://graph.facebook.com/${c.version}/${c.phoneId}/messages`,{method:'POST',headers:{Authorization:'Bearer '+c.token,'Content-Type':'application/json'},body:JSON.stringify({messaging_product:'whatsapp',to:t.phone.replace(/\D/g,''),type:'text',text:{body:text}})});}catch(e){db.prepare('UPDATE outbox SET status=? WHERE id=?').run('unknown',requestId);throw e;}const remoteId=result.messages?.[0]?.id;if(!remoteId){db.prepare('UPDATE outbox SET status=? WHERE id=?').run('unknown',requestId);fail(502,'O provedor não confirmou o envio. Confira antes de tentar novamente.');}const latest=stateRow(db,s.agency_id),thread=latest.state.whatsapp.threads.find(x=>x.id===t.id);thread.messages.push({id:remoteId,role:'team',text,time:new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})});thread.draft='';saveState(db,s.agency_id,latest.state,latest.version,s.user_id);db.prepare('UPDATE outbox SET status=?,remote_id=? WHERE id=?').run('sent',remoteId,requestId);output(res,200,{status:'sent',remoteId});return;}
   if(['/api/payments','/api/signatures','/api/studio/generate'].includes(p)&&method==='POST')fail(501,'Este adaptador será implementado após definir o provedor. Nenhuma operação externa foi realizada.');
   if(p==='/api/audit'&&method==='GET'){output(res,200,{events:db.prepare('SELECT action,created_at FROM audit WHERE agency_id=? ORDER BY id DESC LIMIT 100').all(s.agency_id)});return;}
   fail(404,'Rota não encontrada.');
  }catch(e){const code=e.status||((e.code==='ENOENT')?404:500);if(code===500)console.error('TravelPro request failed:',e.code||e.name);if(!res.headersSent)output(res,code,{error:code===500?'Não foi possível concluir a operação. Tente novamente.':e.message});else res.end();}
 });
 return {server,db,processJobs,setOrigin(value){address=value;},close(){clearInterval(jobTimer);return new Promise(resolve=>server.close(()=>{db.close();resolve();}));}};
}
