import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
test('portal loads persistent empty account and saves linked forms',async()=>{
 const elements=new Map();const elem=()=>({innerHTML:'',textContent:'',value:'',dataset:{},style:{},hidden:false,open:false,classList:{add(){},remove(){},toggle(){}},querySelectorAll(){return[]},querySelector(){return elem()},addEventListener(){},focus(){},showModal(){this.open=true},close(){this.open=false},reportValidity(){return true}});
 const document={querySelector(s){if(!elements.has(s))elements.set(s,elem());return elements.get(s)},querySelectorAll(){return[]},addEventListener(){},body:{dataset:{startRoute:'inicio'}},activeElement:{tagName:'BODY'}};
 const initial=JSON.parse(fs.readFileSync(new URL('../backend/initial-state.json',import.meta.url),'utf8'));initial.agency='Agência integrada';let saved=structuredClone(initial),version=1;
 const api={version:1,user:{id:'u1',name:'Mateus',email:'mateus@example.com'},async session(){return this.user},async request(route,options={}){if(route==='/workspace'&&options.method==='PUT'){assert.equal(options.body.version,version);saved=structuredClone(options.body.state);return {version:++version};}if(route==='/workspace')return {state:structuredClone(saved),version,services:[{service:'openai',configured:false},{service:'operator',configured:false},{service:'whatsapp',configured:false}]};throw Error('Unexpected API route '+route);}};
 const location={pathname:'/portal.html',hash:'',search:''},context={document,window:{TravelAPI:api,scrollTo(){}},location,history:{pushState(a,b,href){const u=new URL(href,'http://localhost');location.pathname=u.pathname;location.search=u.search;location.hash=u.hash;}},addEventListener(){},setInterval(){},setTimeout(){},clearTimeout(){},URL,URLSearchParams,console,structuredClone};vm.createContext(context);
 let source=fs.readFileSync(new URL('../dist/portal.js',import.meta.url),'utf8');source=source.replace(/\}\)\(\);\s*$/,'globalThis.test={state,renderWorkspace,home,agency,workspaceSubmit,snapshot,flush};})();');vm.runInContext(source,context);await new Promise(r=>setImmediate(r));
 const t=context.test;assert.equal(t.state.agency,'Agência integrada');assert.equal(t.state.clients.length,0);
 for(const route of ['whatsapp','leads','agente','cotacao','orcamentos','integracoes','plano','seguranca','faturamento','clientes','agenda','financeiro','roteiros','studio','documentos','configuracoes','travelmatch','vuei']){const html=t.renderWorkspace(route);assert.ok(!html.includes('undefined'),route);assert.ok(html.length>400,route);}
 await t.workspaceSubmit('client',{id:'',name:'Cliente real',phone:'11999990000',email:'cliente@example.com',notes:'Praia'});assert.equal(saved.clients.length,1);const cid=saved.clients[0].id;
 await t.workspaceSubmit('trip',{id:'',title:'Nossa viagem',client:cid,destination:'Brasil',start:'2026-11-01',end:'2026-11-10',travelers:'2',value:'1000',status:'Novo pedido',notes:''});assert.equal(saved.trips.length,1);assert.equal(saved.trips[0].client,cid);
 assert.equal(location.pathname,'/viagem.html');assert.equal(api.version,version);
});
