import test from 'node:test';
import assert from 'node:assert/strict';
import {salesFlow as F,validateState,validateSalesTransition,operatorRequest,operatorResult} from '../backend/validation.mjs';
import {readFileSync} from 'node:fs';
const now=Date.parse('2099-09-29T12:00:00Z');
function fixture(){const s=JSON.parse(readFileSync(new URL('../backend/initial-state.json',import.meta.url)));s.agency='Agência de teste';s.clients=[{id:'c',name:'Ana',phone:'',email:''}];const t={id:'t',client:'c',title:'Portugal',destination:'Portugal',start:'2099-11-01',end:'2099-11-10',travelers:2,value:0,status:'Novo pedido',sales:{quotes:[]}};s.trips=[t];const q={id:'q',trip:'t',client:'c',source:'operator',currency:'BRL',reference:'EU-01',destination:t.destination,start:t.start,end:t.end,travelers:2,validUntil:'2099-09-29T15:00:00-03:00',offers:[{name:'Portugal completo',total:1500,inclusions:['Hotel','Traslado'],terms:'Sujeito à disponibilidade',items:[{name:'Hotel',qty:2,unit:500},{name:'Traslado',qty:1,unit:500}]}]};t.sales.quotes.push(q);t.sales.quoteId='q';return {s,t,q};}
test('quote carries exact prices, inclusions, conditions, original deadline and attendance into proposal',()=>{const {s,t,q}=fixture();const b=F.buildBudget(t,q,0,'b',now);s.budgets.push(b);t.sales.budgetId=b.id;assert.deepEqual(b.items,q.offers[0].items);assert.deepEqual(b.inclusions,['Hotel','Traslado']);assert.equal(b.validUntil,q.validUntil);assert.equal(b.notes,q.offers[0].terms);assert.equal(b.trip,'t');assert.equal(b.client,'c');b.items[0].unit=1;assert.equal(q.offers[0].items[0].unit,500);validateState(s);});
test('package total is not counted once per inclusion; expired and missing deadlines never gain seven days',()=>{const {t,q}=fixture();delete q.offers[0].items;const b=F.buildBudget(t,q,0,'b',now);assert.deepEqual(b.items,[{name:'Portugal completo',qty:1,unit:1500}]);assert.throws(()=>F.buildBudget(t,{...q,validUntil:''},0,'b',now),/validade/);assert.throws(()=>F.buildBudget(t,q,0,'b',Date.parse('2099-09-29T18:00:00Z')),/venceu/);assert.throws(()=>F.buildBudget({...t,id:'other'},q,0,'b',now),/atendimento/);});
test('adapter validates currency, item totals, deadlines and strips unknown sensitive fields',()=>{const {q}=fixture();assert.throws(()=>operatorResult({...q,currency:'USD'}),e=>e.status===502);assert.throws(()=>operatorResult({...q,validUntil:'2099-09-29T18:00'}),/fuso/);const wrong=structuredClone(q);wrong.offers[0].items[0].unit=40;assert.throws(()=>operatorResult(wrong),/total/);q.offers[0].net=100;q.offers[0].commission=40;assert.equal('net' in operatorResult(q).offers[0],false);assert.equal('commission' in operatorResult(q).offers[0],false);});
test('request cannot use client or attendance from another agency',()=>{const {s,t}=fixture();const request={...t,trip:'t',origin:'São Paulo'};assert.equal(operatorRequest(request,s).trip,'t');assert.throws(()=>operatorRequest({...request,client:'foreign'},s));assert.throws(()=>operatorRequest({...request,trip:'foreign'},s));});
test('approval, payment, reservation and emission remain separate; itinerary requires all confirmations',()=>{const {s,t,q}=fixture();const b=F.buildBudget(t,q,0,'b',now);s.budgets.push(b);t.sales.budgetId='b';assert.throws(()=>F.recordDecision(t,b,'approved','WhatsApp',now),/envio/);F.recordDecision(t,b,'sent','Enviada pelo WhatsApp',now);F.recordDecision(t,b,'adjustment','Trocar hotel',now);F.recordDecision(t,b,'sent','Versão revisada enviada',now);F.recordDecision(t,b,'approved','Cliente confirmou',now);assert.equal(F.canItinerary(t),false);const f={reservation:'held',payment:'pending',emission:'pending',reference:'RES-10',deadline:'2099-09-29T20:00:00Z',paymentUrl:'https://pay.example.test/reserva',evidence:'E-mail da operadora'};F.recordFulfillment(t,b,f,now);assert.equal(F.canItinerary(t),false);assert.throws(()=>F.recordFulfillment(t,b,{...f,emission:'issued'},now));assert.throws(()=>F.recordFulfillment(t,b,{...f,paymentUrl:'javascript:alert(1)'},now));F.recordFulfillment(t,b,{...f,reservation:'confirmed',payment:'paid',emission:'issued'},now);assert.equal(F.canItinerary(t),true);assert.equal(t.status,'Confirmada');validateState(s);});
test('server keeps received quotes immutable and blocks new or relinked itineraries before confirmation',()=>{const {s,t}=fixture();const next=structuredClone(s);next.trips[0].sales.quotes[0].offers[0].total=99;assert.throws(()=>validateSalesTransition(s,next),/Preserve/);const r=structuredClone(s);r.itineraries.push({id:'r',trip:t.id,name:'Roteiro',days:[]});assert.throws(()=>validateSalesTransition(s,r),/pagamento/);s.itineraries.push({id:'old',trip:t.id,name:'Roteiro anterior',days:[]});assert.doesNotThrow(()=>validateSalesTransition(s,structuredClone(s)),'historical material stays available');});

test('structured operator details survive proposal creation without leaking internal fields or double counting fees',()=>{const {t,q}=fixture();q.offers[0].details={services:[{kind:'flight',title:'Azul 4151',lines:['Sem bagagem despachada.'],net:10}],paymentTerms:['10 parcelas'],price:{products:1400,fees:100,taxes:0},commission:50};const b=F.buildBudget(t,q,0,'b',now);assert.equal(b.details.services[0].title,'Azul 4151');assert.equal('net' in b.details.services[0],false);assert.equal('commission' in b.details,false);assert.equal(b.items.reduce((sum,i)=>sum+i.qty*i.unit,0),1500);b.details.services[0].lines.push('edited');assert.equal(q.offers[0].details.services[0].lines.length,1);q.offers[0].details.price.fees=101;assert.throws(()=>F.normalizeQuote(q),/total/);assert.throws(()=>F.normalizeDetails({services:[null]}),/serviço/);});
